// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;

namespace addressbooktests
{
    [TestFixture]
    public class ContactTests
    {
        private IWebDriver driver;
        public IDictionary<string, object> Vars { get; private set; }
        private IJavaScriptExecutor js;
        [SetUp]
        public void SetUp()
        {
            driver = new EdgeDriver();
            Vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void NewContactTest()
        {
            OpenHomePage();
            Login(new AccountData("admin", "secret"));
            GoToNewContact();
            ContactData vanya = CreateVanya777();
            FillContactForm(vanya);
            ConfirmAddingNewContact();
            RetornToHomePage();

            ContactData CreateVanya777()
            {
                ContactData contact = new ContactData("Vanya777");
                contact.FirstName = "Ivan";
                contact.MiddleName = "Ivanovich";
                contact.LastName = "Ivanov";
                contact.Title = "Software Engineer";
                contact.Company = "Emerson";
                contact.Address = "St. Petersburg";
                contact.Home = "St. Petersburg";
                contact.Mobile = "777777";
                contact.Email = "Ivanov@mail.ru";
                contact.Bday = new string[] { "7", "July", "1907" };
                return contact;
            }
        }

        private void RetornToHomePage()
        {
            driver.FindElement(By.LinkText("home page")).Click();
            driver.Manage().Window.Size = new System.Drawing.Size(1920, 1036);
        }

        private void ConfirmAddingNewContact()
        {
            driver.FindElement(By.CssSelector("input:nth-child(87)")).Click();
        }

        private void FillContactForm(ContactData contact)
        {
            driver.FindElement(By.Name("firstname")).Click();
            driver.FindElement(By.Name("firstname")).SendKeys(contact.FirstName);
            driver.FindElement(By.Name("middlename")).SendKeys(contact.MiddleName);
            driver.FindElement(By.Name("lastname")).SendKeys(contact.LastName);
            driver.FindElement(By.Name("nickname")).SendKeys(contact.NickName);
            driver.FindElement(By.Name("title")).Click();
            driver.FindElement(By.Name("title")).SendKeys(contact.Title);
            driver.FindElement(By.Name("company")).SendKeys(contact.Company);
            driver.FindElement(By.Name("address")).SendKeys(contact.Address);
            driver.FindElement(By.Name("home")).SendKeys(contact.Home);
            driver.FindElement(By.Name("mobile")).SendKeys(contact.Mobile);
            driver.FindElement(By.Name("email")).SendKeys(contact.Email);
            driver.FindElement(By.Name("bday")).Click();
            {
                var dropdown = driver.FindElement(By.Name("bday"));
                dropdown.FindElement(By.XPath($"//option[. = {contact.Bday[0]}]")).Click();
            }
            driver.FindElement(By.Name("bmonth")).Click();
            {
                var dropdown = driver.FindElement(By.Name("bmonth"));
                dropdown.FindElement(By.XPath($"//option[. = '{contact.Bday[1]}']")).Click();
            }
            driver.FindElement(By.Name("byear")).Click();
            driver.FindElement(By.Name("byear")).SendKeys(contact.Bday[2]);
        }

        private void GoToNewContact()
        {
            driver.FindElement(By.LinkText("add new")).Click();
        }

        private void Login(AccountData account)
        {
            driver.FindElement(By.Name("user")).SendKeys(account.Username);
            driver.FindElement(By.Name("pass")).SendKeys(account.Password);
            driver.FindElement(By.CssSelector("input:nth-child(7)")).Click();
        }

        private void OpenHomePage()
        {
            driver.Navigate().GoToUrl("http://localhost/addressbook/");
        }
    }
}