// Generated by Selenium IDE
using OpenQA.Selenium;
using NUnit.Framework;

namespace addressbooktests
{
    [TestFixture]
    public class GroupTests : TestBase
    {        
        [Test]
        public void NewGroupTest()
        {
            app.NavigationHelper.GoToGroupsPage();
            GroupData group = new GroupData("aaa");
            group.Header = "sss";
            group.Footer = "ddd";
            app.GroupHelper.CreateNewGroup(group);
            app.NavigationHelper.GoToGroupsPage();
        }
    }
}