// Generated by Selenium IDE
using System.Collections.Generic;
using OpenQA.Selenium;
using OpenQA.Selenium.Edge;
using NUnit.Framework;

namespace addressbooktests
{
    [TestFixture]
    public class GroupTests
    {
        private IWebDriver driver;
        public IDictionary<string, object> Vars { get; private set; }
        [SetUp]
        public void SetUp()
        {
            driver = new EdgeDriver();
            Vars = new Dictionary<string, object>();
        }
        [TearDown]
        protected void TearDown()
        {
            driver.Quit();
        }
        [Test]
        public void NewGroupTest()
        {
            driver.Navigate().GoToUrl("http://localhost/addressbook/");
            driver.Manage().Window.Size = new System.Drawing.Size(1920, 1036);
            driver.FindElement(By.Name("user")).Click();
            driver.FindElement(By.Name("user")).SendKeys("admin");
            driver.FindElement(By.Name("pass")).SendKeys("secret");
            driver.FindElement(By.CssSelector("input:nth-child(7)")).Click();
            driver.FindElement(By.LinkText("groups")).Click();
            driver.FindElement(By.Name("new")).Click();
            driver.FindElement(By.Name("group_name")).Click();
            driver.FindElement(By.Name("group_name")).SendKeys("q");
            driver.FindElement(By.Name("group_header")).SendKeys("q");
            driver.FindElement(By.Name("group_footer")).SendKeys("q");
            driver.FindElement(By.Name("submit")).Click();
            driver.FindElement(By.LinkText("groups")).Click();
        }
    }
}